modLoader="javafml"
loaderVersion="[40,)"
license="Apache-2.0"
issueTrackerURL="${discordUrl}"
displayURL="${sourceUrl}"

[[mods]]
modId="bteterrarenderer"
version="${version}"
displayName="${displayName}"
logoFile="icon.png" # The path should not contain slashes or backslashes
credits="${credits}"
authors="${authors}"
description='''
${description}
'''

[[dependencies.bteterrarenderer]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.24,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bteterrarenderer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"