# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run core project tests
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: :core:test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build core with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: :core:build

      - name: Build subprojects with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: copyBuildResultToRoot

      - uses: actions/upload-artifact@v3
        with:
          name: Build result
          path: build/libs/*.jar